module.exports = [
  ['前端综合', 'HTML', 'HTML语义化的好处？', '代码可读性强、SEO友好、无障碍、维护性好。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'HTML', 'meta标签的常用属性？', 'charset、name、content、http-equiv等。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'HTML', 'a标签的target属性？', '_self、_blank、_parent、_top等。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'HTML', '图片懒加载怎么实现？', 'loading="lazy"、Intersection Observer、scroll事件监听。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'HTML', '表单元素有哪些？', 'input、select、textarea、button、label、fieldset等。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', 'CSS选择器优先级？', 'ID > 类/属性/伪类 > 标签/伪元素；!important最高。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', '盒模型的两种模式？', '标准盒模型(content-box)、怪异盒模型(border-box)。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', '清除浮动的方法？', 'clear、overflow、伪元素、BFC等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', 'BFC是什么？怎么触发？', '块级格式化上下文；overflow:hidden、display:flex等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', 'flex布局常用属性？', 'display:flex、flex-direction、justify-content、align-items等。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', 'grid布局相比flex有什么优势？', '二维布局更灵活，适合网格类场景。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', 'CSS动画的方式？', 'transition、animation、transform。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', '预处理器Sass/Less的优点？', '变量、嵌套、混合、继承、函数等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', 'CSS变量怎么用？', '--变量名:值；var(--变量名)。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', '响应式布局常用方案？', '媒体查询、百分比、rem、vw/vh、flex/grid。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', '1px边框问题怎么解决？', '伪元素+transform:scale(0.5)等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'CSS', 'z-index在什么情况下无效？', '未定位(static)、父级z-index低、同一层叠上下文内。', 'hard', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', 'JS数据类型有哪些？', '基本类型：Number、String、Boolean、Null、Undefined、Symbol、BigInt；引用类型：Object。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', 'typeof null为什么是object？', '历史遗留bug，null的类型标签是0，与object相同。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '==和===的区别？', '==会类型转换，===不转换直接比较。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '闭包是什么？', '函数能访问外部作用域变量，即使外部函数已返回。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '原型链继承的原理？', '实例通过__proto__指向原型，形成链；查找属性沿链往上。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', 'this指向的几种情况？', '默认绑定、隐式绑定、显式绑定(call/apply/bind)、new绑定。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', 'new操作符做了什么？', '创建空对象、绑定原型、绑定this、返回对象。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '事件流的三个阶段？', '捕获、目标、冒泡。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '事件委托(代理)的好处？', '减少事件监听、动态元素也能响应。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '事件循环Event Loop？', '调用栈、宏任务、微任务；微任务先于宏任务执行。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', 'Promise有什么用？状态？', '解决回调地狱；pending、fulfilled、rejected。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', 'async/await的原理？', '语法糖，基于Promise。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '深拷贝怎么实现？', 'JSON.parse(JSON.stringify())、递归拷贝、lodash.cloneDeep。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '防抖和节流的区别？', '防抖：事件触发后延迟执行，期间再触发则重置；节流：固定时间只执行一次。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'JS', '数组常用方法？', 'forEach、map、filter、reduce、find、some、every等。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'DOM', 'DOM操作常用API？', 'querySelector、getElementById、createElement、appendChild等。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'DOM', '虚拟DOM是什么？', '用JS对象表示真实DOM，diff后最小化更新。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'DOM', 'diff算法的大概原理？', '同级比较、key优化、双端对比。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '网络', 'HTTP状态码常见的有哪些？', '200成功、301永久重定向、302临时、304协商缓存、400请求错误、401未授权、403禁止、404未找到、500服务器错误。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', '网络', 'HTTP和HTTPS区别？', 'HTTPS加密，更安全；端口443 vs 80。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '网络', '强缓存和协商缓存？', '强缓存：Cache-Control/Expires；协商缓存：Last-Modified/ETag。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '网络', '跨域怎么解决？', 'CORS、JSONP、代理、postMessage、iframe等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '网络', 'Cookie和Session区别？', 'Cookie存客户端，Session存服务端；Session依赖Cookie存sessionId。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '网络', 'LocalStorage、SessionStorage、Cookie的区别？', '容量、过期时间、是否随请求发送、作用域。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'Vue', 'Vue2和Vue3的区别？', 'Composition API、响应式原理(Proxy)、性能优化、TS支持等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'Vue', 'Vue响应式原理？', 'Vue2用Object.defineProperty；Vue3用Proxy。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'Vue', 'computed和watch区别？', 'computed有缓存，适合计算；watch适合监听变化执行逻辑。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'Vue', 'v-if和v-show区别？', 'v-if真销毁重建，v-show只是display:none切换。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'Vue', 'Vuex/Pinia的作用？', '状态管理，共享组件间数据。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'Vue', 'Vue-Router的两种模式？', 'Hash模式(#)、History模式(pushState)。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'React', 'React Hooks解决了什么问题？', '逻辑复用、组件状态管理、避免class组件复杂度。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'React', 'useState和useEffect的使用？', 'useState管理状态；useEffect处理副作用。', 'easy', 'seed,frontend', 'frontend'],
  ['前端综合', 'React', 'useMemo和useCallback？', 'useMemo缓存计算结果，useCallback缓存函数，用于性能优化。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', 'React', 'React虚拟DOM和diff？', '类似Vue，React用Fiber架构。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '性能', '前端性能优化方向？', '加载优化、渲染优化、缓存、资源优化、代码优化。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '工具', 'Webpack和Vite的区别？', 'Webpack基于bundle；Vite基于ES Module，开发阶段快。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '工具', 'Git常用命令？', 'add、commit、push、pull、merge、rebase、reset等。', 'easy', 'seed,frontend', 'frontend']
];
