module.exports = [
  ['Go综合', '并发编程', 'Go的Goroutine和OS线程有什么区别？', 'Goroutine由Go运行时调度，占用内存更小（初始2KB），切换成本更低；OS线程由内核调度，占用内存大（MB级），切换成本高。', 'medium', 'seed,go', 'go'],
  ['Go综合', '并发编程', 'Go的调度器GMP模型中M、G、P分别代表什么？', 'M：Machine，操作系统线程；G：Goroutine，Go协程；P：Processor，处理器，包含本地G队列。', 'medium', 'seed,go', 'go'],
  ['Go综合', '并发编程', '什么是工作窃取（Work Stealing）？', '当P的本地G队列为空时，从其他P的队列尾部窃取一半G来执行，提高CPU利用率。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Channel', '无缓冲和有缓冲Channel的区别？', '无缓冲Channel：发送和接收必须同时就绪，否则阻塞；有缓冲Channel：有容量，只要没满就可以发送。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Channel', '如何安全关闭Channel？', '发送方负责关闭Channel，接收方通过v, ok := <-ch判断是否关闭。不要在接收方关闭。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Channel', '什么是Channel的方向特性？', 'Channel可以指定为只读(<-chan)或只写(chan<-)，增加类型安全。', 'medium', 'seed,go', 'go'],
  ['Go综合', '并发控制', 'sync.Mutex和sync.RWMutex的区别？', 'Mutex互斥锁，读写都加锁；RWMutex读写锁，读可以并发，写独占。', 'medium', 'seed,go', 'go'],
  ['Go综合', '并发控制', 'sync.Once的作用是什么？', 'sync.Once保证某个函数只执行一次，常用于单例初始化。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'context', 'context包的用途和常用方法？', '用于传递取消信号、超时控制、元数据；常用WithCancel、WithTimeout、WithDeadline。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'context', 'context是如何传递取消信号的？', '通过内部的Done() channel，当取消时channel被关闭，<-ctx.Done()会收到信号。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'error处理', 'Go的错误处理方式和其他语言有什么不同？', 'Go使用返回值显式返回error，不使用异常；鼓励开发者显式处理错误。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'error处理', '如何自定义error类型？', '实现error接口，该接口只有Error() string方法即可。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'error处理', 'Go 1.13+的errors包新增了什么功能？', 'Is/As/Unwrap，用于错误链判断和包装/解包。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'recover', 'recover()只能在什么时候生效？', '只能在defer函数中调用，用于恢复panic。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'interface', 'Go的空接口interface{}有什么用途？', '可以接收任意类型，类似Java的Object，但Go不建议滥用。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'interface', '类型断言x.(T)和类型选择switch x.(type)的区别？', '类型断言检查x是否为T类型；类型选择可以根据不同类型执行不同逻辑。', 'medium', 'seed,go', 'go'],
  ['Go综合', '反射', 'Go的反射reflect包可以做什么？', '运行时获取类型信息、调用方法、读写字段；反射比较慢且复杂，应避免滥用。', 'medium', 'seed,go', 'go'],
  ['Go综合', '反射', 'reflect.Value和reflect.Type的区别？', 'Type是类型信息，Value是值信息；Type不包含具体值，Value包含。', 'medium', 'seed,go', 'go'],
  ['Go综合', '内存分配', 'Go的栈和堆如何分配？', 'Go通过逃逸分析决定变量在栈还是堆；栈自动管理，堆由GC管理。', 'medium', 'seed,go', 'go'],
  ['Go综合', '垃圾回收', 'Go GC的发展历程？', '1.5三色标记并发GC，1.8写屏障+混合屏障，1.13异步清扫等。', 'medium', 'seed,go', 'go'],
  ['Go综合', '垃圾回收', 'Go的GC触发条件有哪些？', '堆内存达到阈值、定时触发、手动调用runtime.GC()。', 'medium', 'seed,go', 'go'],
  ['Go综合', '性能调优', 'Go常用的性能分析工具？', 'pprof、trace、benchmark、go tool等。', 'medium', 'seed,go', 'go'],
  ['Go综合', '性能调优', '如何用pprof分析性能问题？', '通过net/http/pprof引入，访问/debug/pprof，用go tool pprof分析。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Web框架', 'Gin框架的中间件机制？', '洋葱模型，按注册顺序执行；c.Next()调用后续中间件。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Web框架', 'Gin参数绑定的标签有哪些？', 'form、json、uri、header、xml等，对应不同请求来源。', 'medium', 'seed,go', 'go'],
  ['Go综合', '数据库', 'Go标准库database/sql的设计？', '接口化设计，不同驱动实现相同接口；支持连接池。', 'medium', 'seed,go', 'go'],
  ['Go综合', '数据库', 'sql预处理怎么用？为什么要预处理？', 'db.Prepare()预编译语句；防止SQL注入，提高性能。', 'medium', 'seed,go', 'go'],
  ['Go综合', '并发模式', '什么是扇出扇入模式？', '扇出：启动多个Goroutine处理；扇入：将结果合并到一个Channel。', 'medium', 'seed,go', 'go'],
  ['Go综合', '并发模式', '超时控制如何实现？', 'select + time.After()，或context.WithTimeout()。', 'medium', 'seed,go', 'go'],
  ['Go综合', '并发模式', '如何实现限流器？', '令牌桶、漏桶；用channel或golang.org/x/time/rate。', 'medium', 'seed,go', 'go'],
  ['Go综合', '依赖管理', 'go mod的使用流程？', 'go mod init → go get → go build。', 'medium', 'seed,go', 'go'],
  ['Go综合', '依赖管理', 'go.mod和go.sum的区别？', 'go.mod定义依赖；go.sum记录版本哈希保证安全。', 'medium', 'seed,go', 'go'],
  ['Go综合', '测试', 'Go的测试文件格式？', 'xxx_test.go，在同包下；Test开头函数。', 'medium', 'seed,go', 'go'],
  ['Go综合', '测试', '如何做表驱动测试？', '构建测试用例数组，循环遍历执行。', 'medium', 'seed,go', 'go'],
  ['Go综合', '测试', '基准测试(benchmark)的规则？', 'Benchmark开头，*testing.B参数，循环b.N次。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Slice', 'Slice的len和cap的区别？', 'len是元素个数，cap是底层数组容量。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Slice', 'make创建slice时指定len和cap有什么好处？', '减少扩容，提升性能。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Map', 'Go的map为什么不是并发安全的？', '没有内置锁；并发读写会panic，需加sync.Mutex或用sync.Map。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'Map', 'map的遍历顺序是固定的吗？', '不是，Go故意随机化起始点，避免依赖顺序。', 'medium', 'seed,go', 'go'],
  ['Go综合', '字符串', 'Go的string是可变还是不可变的？', '不可变；修改需转为[]byte或[]rune，修改后再转回去。', 'medium', 'seed,go', 'go'],
  ['Go综合', '函数', 'Go的函数可以作为参数和返回值吗？', '可以，Go支持高阶函数。', 'medium', 'seed,go', 'go'],
  ['Go综合', '函数', '什么是闭包？', '函数捕获外部变量，即使函数返回外部变量仍然有效。', 'medium', 'seed,go', 'go'],
  ['Go综合', '方法', '方法和函数的区别？', '方法有接收者(receiver)，只能和接收者类型绑定。', 'medium', 'seed,go', 'go'],
  ['Go综合', '接收者', '值接收者和指针接收者的区别？', '值接收者不修改原对象；指针接收者可以修改。', 'medium', 'seed,go', 'go'],
  ['Go综合', '组合', 'Go的结构体嵌入(struct embedding)是继承吗？', '不是继承，是组合；没有多态，但有类型提升。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'defer', '多个defer的执行顺序？', '后进先出(LIFO)。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'defer', 'defer什么时候求值？', 'defer的参数在注册时就已经求值。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'init', 'init()函数的特点？', '自动在main()前执行，可以有多个，按源文件顺序执行。', 'medium', 'seed,go', 'go'],
  ['Go综合', 'main', 'main包和main函数的关系？', '只有main包的main函数才是程序入口。', 'medium', 'seed,go', 'go']
];
