module.exports = [
  ['数据库综合', 'MySQL', '数据库三大范式？', '1NF：属性原子性；2NF：非主键完全依赖主键；3NF：非主键不传递依赖主键。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'MySQL的存储引擎InnoDB和MyISAM区别？', 'InnoDB支持事务、外键、行锁、MVCC；MyISAM不支持，表锁，查询快。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'InnoDB的索引结构？', 'B+树；聚簇索引，叶子节点存数据。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '聚簇索引和非聚簇索引区别？', '聚簇索引叶子节点是数据；非聚簇索引叶子节点是主键。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '索引的类型有哪些？', '普通、唯一、主键、联合、全文等。', 'easy', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '什么是最左前缀原则？', '联合索引从左往右匹配，遇到范围查询停止。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '索引失效的情况？', 'like%前缀、函数、类型转换、or、is null/is not null等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '事务的ACID特性？', '原子性、一致性、隔离性、持久性。', 'easy', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'MySQL的隔离级别？', '读未提交、读已提交、可重复读、串行化；默认可重复读。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '什么是脏读、幻读、不可重复读？', '脏读：读未提交；不可重复读：同一事务两次读同一行不同；幻读：同一事务两次读同一范围行数不同。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'MVCC是什么？', '多版本并发控制；通过undo log、Read View实现，不加锁读。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'MySQL的锁机制？', '行锁、表锁；共享锁、排他锁；意向锁；Gap锁、Next-Key锁。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'MySQL日志有哪些？', 'binlog、redo log、undo log、error log、slow log等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '主从复制原理？', 'master写binlog，slave拉取binlog回放。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'SQL优化的一般思路？', '加索引、避免全表扫描、优化SQL写法、表结构优化、分库分表。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', 'EXPLAIN关键字怎么用？', 'EXPLAIN SQL语句；看type、key、rows、Extra等字段。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MySQL', '分库分表的策略？', '垂直拆分、水平拆分；按范围、哈希、取模等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis数据类型？', 'String、Hash、List、Set、ZSet、HyperLogLog、Geo、Stream等。', 'easy', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis是单线程的吗？为什么快？', '核心模型是单线程；基于内存、IO多路复用、高效数据结构。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis持久化机制？', 'RDB快照、AOF日志、混合持久化。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis过期策略？', '定期删除+惰性删除。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis内存淘汰策略？', 'LRU、LFU、随机等；8种策略。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis缓存三大问题？', '缓存穿透、缓存击穿、缓存雪崩。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', '怎么解决缓存穿透？', '布隆过滤器、缓存空值。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', '怎么解决缓存击穿？', '互斥锁、逻辑过期。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', '怎么解决缓存雪崩？', '过期时间随机、集群、降级。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis的事务？', 'MULTI、EXEC、DISCARD；不支持回滚。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis发布订阅？', 'PUBLISH、SUBSCRIBE；消息队列简单实现。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis Cluster集群模式？', '哈希槽16384个，节点分片存储。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'Redis', 'Redis应用场景？', '缓存、排行榜、计数器、分布式锁、会话存储等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'MongoDB', 'MongoDB是什么类型数据库？', '文档型NoSQL；BSON存储。', 'easy', 'seed,database', 'database'],
  ['数据库综合', 'MongoDB', 'MongoDB和MySQL适用场景对比？', 'Mongo适合灵活schema、读写量大、事务要求不高；MySQL适合关系复杂、强事务。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'PostgreSQL', 'PostgreSQL相比MySQL的优势？', '更标准SQL、支持复杂查询、JSON支持更好、插件丰富。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '消息队列', '为什么用消息队列？', '异步、解耦、削峰填谷。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '消息队列', 'Kafka和RabbitMQ对比？', 'Kafka吞吐高、适合日志/大数据；RabbitMQ功能全、延时低、适合业务。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '消息队列', '消息队列如何保证不丢失？', '生产端确认、持久化、消费端确认。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '消息队列', '消息重复消费怎么处理？', '幂等性设计，如唯一ID、数据库唯一键。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '分布式', 'CAP定理？', '一致性、可用性、分区容错性；三者选二。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '分布式', 'BASE理论？', 'Basically Available、Soft state、Eventually consistent；CAP的折中。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '分布式', '分布式事务解决方案？', '2PC、3PC、TCC、本地消息表、Saga、Seata等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '分布式', '分布式ID生成方案？', 'UUID、数据库自增、Redis、雪花算法、美团Leaf等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '分布式', '分布式锁实现？', 'Redis(setnx)、ZooKeeper、数据库。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'SQL', 'JOIN有哪几种？', 'INNER JOIN、LEFT JOIN、RIGHT JOIN、FULL JOIN。', 'easy', 'seed,database', 'database'],
  ['数据库综合', 'SQL', 'UNION和UNION ALL区别？', 'UNION去重排序；UNION ALL直接合并。', 'easy', 'seed,database', 'database'],
  ['数据库综合', 'SQL', 'COUNT(*), COUNT(1), COUNT(列)区别？', 'InnoDB下COUNT(*)和COUNT(1)差不多；COUNT(列)不计NULL。', 'medium', 'seed,database', 'database'],
  ['数据库综合', 'SQL', 'WHERE和HAVING区别？', 'WHERE在聚合前过滤行；HAVING在聚合后过滤组。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '其他', '什么是读写分离？', '主库写，从库读，分担压力。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '其他', '什么是冷备热备？', '冷备：停机备份；热备：在线备份。', 'medium', 'seed,database', 'database']
];
