module.exports = [
  ['DevOps综合', 'Linux', 'Linux常用命令有哪些？', 'ls、cd、pwd、cat、grep、find、ps、top、netstat、curl、wget、tar、chmod、chown等。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '查看文件内容的命令？', 'cat、more、less、head、tail。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '查找文件的命令？', 'find、locate、which、whereis。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', 'grep的常见用法？', 'grep pattern file；-i忽略大小写，-v反向，-r递归，-n显示行号。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', 'sed和awk的作用？', 'sed流编辑器，awk文本处理语言。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '查看进程的命令？', 'ps、top、htop、pstree。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '如何查看端口占用？', 'netstat、ss、lsof -i:端口。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '文件权限怎么看？', 'ls -l；r读4、w写2、x执行1。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '软硬链接区别？', '硬链接同inode，软链接是快捷方式。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', 'Shell脚本的shebang？', '#!/bin/bash或#!/bin/sh。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '如何后台运行程序？', '&、nohup、screen、tmux、systemd服务。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '定时任务crontab怎么用？', '分 时 日 月 周 命令；crontab -e编辑。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '系统负载怎么看？', 'uptime、top、w；load average三个值。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '磁盘空间怎么查看？', 'df、du。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Linux', '日志管理常用工具？', 'journald、syslog、logrotate。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '网络', '网络诊断常用命令？', 'ping、traceroute、mtr、telnet、nc、tcpdump、dig、nslookup。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '网络', 'TCP和UDP区别？', 'TCP面向连接、可靠、有序；UDP无连接、不可靠、高效。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '网络', 'HTTP和HTTPS？', 'HTTPS加了TLS/SSL加密，443端口。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', '网络', 'DNS解析流程？', '浏览器缓存→系统缓存→hosts→DNS服务器。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'Docker的三个核心概念？', '镜像Image、容器Container、仓库Repository。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'Dockerfile常用指令？', 'FROM、RUN、COPY、ADD、WORKDIR、EXPOSE、CMD、ENTRYPOINT、ENV、ARG等。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'COPY和ADD的区别？', 'ADD多了自动解压和远程URL功能；一般推荐COPY。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'CMD和ENTRYPOINT的区别？', 'CMD是默认命令可被覆盖；ENTRYPOINT是入口命令，参数追加。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'Docker镜像分层原理？', 'UnionFS联合文件系统，每层只读，容器层可写。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', '如何优化Docker镜像？', '选用小基础镜像、减少层、.dockerignore、多阶段构建。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'Docker数据卷volume？', '持久化数据，绕过容器文件系统。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'Docker网络模式？', 'bridge、host、none、container、自定义网络。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Docker', 'Docker Compose的作用？', '定义和运行多容器应用，docker-compose.yml。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', 'Kubernetes核心组件？', 'Master：etcd、apiserver、scheduler、controller-manager；Node：kubelet、kube-proxy、容器运行时。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', 'Pod是什么？', '最小调度单元，一个或多个容器，共享网络和存储。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', 'K8s常用控制器？', 'Deployment、StatefulSet、DaemonSet、Job、CronJob等。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', 'Service有哪些类型？', 'ClusterIP、NodePort、LoadBalancer、ExternalName。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', 'Ingress的作用？', 'HTTP/HTTPS路由入口，域名访问服务。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', 'ConfigMap和Secret？', '配置和敏感数据管理，解耦配置。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', '健康检查探针？', 'livenessProbe存活探针、readinessProbe就绪探针。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'K8s', '资源限制requests和limits？', 'requests是最低资源，limits是最高资源。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'CI/CD', '什么是CI/CD？', 'Continuous Integration持续集成，Continuous Delivery/Deployment持续交付/部署。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'CI/CD', '常见CI/CD工具？', 'Jenkins、GitLab CI、GitHub Actions、CircleCI、Travis CI、ArgoCD等。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'CI/CD', 'GitFlow工作流？', 'master、develop、feature、release、hotfix分支。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '监控', '常见监控工具？', 'Prometheus+Grafana、Zabbix、ELK、Jaeger、Skywalking等。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '监控', 'Prometheus的核心组件？', 'TSDB时序数据库、Pull模式采集、PromQL查询、Alertmanager告警。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '监控', '什么是APM？', 'Application Performance Management应用性能监控。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '日志', 'ELK是什么？', 'Elasticsearch、Logstash、Kibana；日志收集、存储、可视化。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '安全', '常见安全扫描工具？', 'SonarQube代码质量、Trivy镜像漏洞、OWASP ZAP等。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', 'Git', 'Git常用命令？', 'add、commit、push、pull、branch、checkout、merge、rebase、stash、reset等。', 'easy', 'seed,devops', 'devops'],
  ['DevOps综合', 'Git', 'git merge和git rebase区别？', 'merge保留历史，rebase线性历史。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '其他', '什么是IaC？', 'Infrastructure as Code基础设施即代码，Terraform、Ansible等。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '其他', 'Ansible的作用？', '自动化配置管理、应用部署、任务执行。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '其他', '什么是灰度发布/金丝雀发布？', '逐步放量，小部分用户先用，没问题再全量。', 'medium', 'seed,devops', 'devops'],
  ['DevOps综合', '其他', '回滚策略有哪些？', '版本回退、蓝绿部署、快速修复重新发布。', 'medium', 'seed,devops', 'devops']
];
