module.exports = [
  ['数据库综合', '种子题', 'MySQL存储引擎InnoDB和MyISAM的区别？', 'InnoDB支持事务和外键，行级锁，适合高并发。MyISAM不支持事务，表级锁，查询稍快，适合读多写少。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MySQL索引为什么用B+树而不用B树？', 'B+树查询更稳定，叶子结点有链表便于范围查询，磁盘IO更少，适合存储大量数据。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'EXPLAIN执行计划的key_len和rows列表示什么？', 'key_len是使用的索引长度，rows是预计扫描的行数。结合起来判断索引效率。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '什么是覆盖索引？有什么优势？', '覆盖索引是查询字段都在索引中，无需回表查数据。减少IO，性能更好。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MySQL最左前缀原则如何理解？', '复合索引从最左开始匹配，不能跳过列。例如(a,b,c)索引，查询a或a,b可以用索引，查b,c不行。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '什么是索引下推(ICP)？', 'ICP允许在存储引擎层用索引过滤数据，减少回表，提升性能。MySQL 5.6+支持。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MySQL事务的ACID特性分别指什么？', '原子性、一致性、隔离性、持久性。保证数据正确和并发安全。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'SQL事务的四个隔离级别？', '读未提交、读已提交、可重复读、串行化。逐级隔离性增强，性能降低。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '什么是脏读、幻读、不可重复读？', '脏读读到未提交数据，不可重复读同一查询结果不同，幻读同一查询行数不同。隔离级别可以解决这些问题。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'InnoDB的MVCC是如何工作的？', 'MVCC通过undo log和read view实现多版本并发控制，读写不阻塞。RC和RR级别实现不同。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'InnoDB行锁有哪些类型？', 'Record Lock(记录锁)、Gap Lock(间隙锁)、Next-Key Lock(临键锁，前两者组合)。用于防止幻读。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MySQL死锁的原因和处理？', '两个事务互相等待对方锁。查看show engine innodb status，分析死锁日志。合理设计索引和事务顺序避免。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'Redis常用数据类型及应用场景？', 'String(缓存)、Hash(对象)、List(队列)、Set(去重、交集)、Sorted Set(排行榜)。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'Redis持久化方式RDB和AOF的对比？', 'RDB是快照，恢复快，可能丢数据。AOF是日志，更安全，文件大。可以混合使用。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'Redis缓存穿透、击穿、雪崩的区别和解决？', '穿透是查不存在数据→布隆过滤器；击穿是热点key失效→互斥锁/永不过期；雪崩是大量key同时失效→随机过期时间。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'Redis分布式锁的实现和注意事项？', '用SET key value NX PX实现。注意锁超时、释放、可重入。用Redisson更稳健。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'Redis Cluster的槽位分片机制？', '16384个槽位，每个节点负责一部分。CRC16(key)计算应该到哪个槽，实现集群扩展。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MongoDB文档模型的优缺点？', '优点灵活、嵌套文档减少join。缺点join弱，事务支持有限，不适合强一致性场景。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MongoDB聚合管道的常用阶段？', '$match、$group、$sort、$project、$lookup、$unwind等。可以组合多个操作。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MongoDB索引和MySQL索引的区别？', 'MongoDB支持多键索引、地理空间索引、全文索引。底层实现类似，但MongoDB更灵活。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MongoDB副本集的作用和组成？', '副本集提供高可用，有一个Primary多个Secondary。Primary写，Secondaries读和备份。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'MongoDB分片策略有哪些？', '范围分片、哈希分片、区域分片。选择合适的shard key很重要，避免热点。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'PostgreSQL相比MySQL的优势？', 'PostgreSQL支持更复杂查询、JSONB、窗口函数、CTE、全文搜索等。适合复杂数据分析场景。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'PostgreSQL JSONB类型的用途？', 'JSONB存储JSON的二进制格式，支持索引，查询速度比JSON快。适合存储半结构化数据。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'PostgreSQL窗口函数的常见应用？', 'ROW_NUMBER、RANK、SUM OVER、AVG OVER等。用于排名、累计、分组计算。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'PostgreSQL CTE(公共表表达式)的好处？', 'CTE可以编写更清晰的递归查询，分解复杂查询，提高可读性。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'PostgreSQL分区表的类型和用途？', '范围、列表、哈希分区。可以将大表拆分，提高查询性能和管理效率。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'CAP定理是指什么？', '一致性、可用性、分区容错性三者不可兼得。系统设计时要权衡。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '分布式一致性模型有哪些？', '强一致性、线性一致性、因果一致性、最终一致性等。不同场景选择不同。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '分库分表的分片策略有哪些？', '范围、哈希、取模、地理位置等。还要考虑扩容和数据迁移问题。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'NewSQL数据库的代表和特点？', 'TiDB、CockroachDB等。兼顾传统SQL和NoSQL的扩展能力。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '数据库三范式和反范式的权衡？', '范式减少冗余，但增加join。反范式提高查询性能，适合读多写少。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '数据库ER模型设计的步骤？', '确定实体、属性、关系，画ER图，转换为关系模式，规范化。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '数据库迁移工具的选择？', 'Flyway、Liquibase等。Flyway简单，Liquibase更灵活，支持XML/YAML/JSON/SQL。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'SQL慢查询的常见优化思路？', '加索引、优化查询语句、避免select *、分页优化、冷热数据分离。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '数据库主从延迟的原因和解决？', '主从复制异步导致。解决方案：读写分离时强制读主、等待同步、业务接受延迟等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '数据库连接池配置最佳实践？', '设置合理的最大/最小连接数、超时时间、连接验证。HikariCP是高性能选择。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '如何设计数据库读写分离？', '应用层判断路由、中间件代理(ShardingSphere)、数据库驱动等方式。注意主从一致性。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'SQL注入的原理和防护？', '注入恶意SQL片段。防护：参数化查询、输入验证、ORM框架、最小权限原则。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '时序数据库的特点和代表？', 'InfluxDB、Prometheus等。专门处理时间序列数据，写入高效，保留策略。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '图数据库的应用场景？', 'Neo4j、JanusGraph等。适合社交关系、推荐系统、知识图谱等关系复杂场景。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '列式数据库和行式数据库的区别？', '列式存储适合OLAP分析查询，压缩率高。行式适合OLTP事务查询。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'ClickHouse的核心特点？', '列式存储，向量化执行，查询极快。适合大数据量分析，不适合频繁更新。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'Elasticsearch倒排索引的原理？', '分词后建立term到文档的映射，适合全文搜索。相关度通过TF-IDF或BM25计算。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '数据库备份策略的最佳实践？', '定期全备+增量备份，离线备份，验证恢复，多地存储，自动化。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '如何监控数据库性能？', 'Prometheus+Grafana、慢查询日志、show status、Performance Schema等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '数据库高可用方案有哪些？', '主从复制、主主复制、MHA、Orchestrator、Paxos/Raft共识算法等。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', '什么是数据库连接泄漏？如何避免？', '连接使用后未归还导致耗尽。使用try-with-resources或ORM自动管理。', 'medium', 'seed,database', 'database'],
  ['数据库综合', '种子题', 'NoSQL数据库分类和适用场景？', '键值(Redis)、文档(MongoDB)、列族(HBase)、图(Neo4j)。根据数据模型选择。', 'medium', 'seed,database', 'database']
];
