module.exports = [
  ['前端综合', '种子题', 'HTML5语义化标签的优点有哪些？', '语义化标签提高代码可读性，便于维护，对SEO友好，屏幕阅读器等辅助技术支持更好。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Flexbox和Grid布局的适用场景是什么？', 'Flexbox适合一维布局，行或列方向。Grid适合二维布局，可以同时控制行和列。两者可以结合使用。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'CSS Grid中的grid-template-areas有什么用？', 'grid-template-areas可以创建直观的布局模板，用区域名称定位元素，代码可读性高。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', '响应式设计的核心技术有哪些？', '媒体查询、弹性布局、相对单位(em/rem/vw/vh)、响应式图片等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'CSS动画和requestAnimationFrame的性能对比？', 'CSS动画由浏览器优化，性能通常更好。requestAnimationFrame更灵活，适合复杂动画。优先使用transform和opacity。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'BEM命名规范的优势是什么？', 'BEM代表Block-Element-Modifier，提高CSS可维护性和可复用性，避免命名冲突。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'CSS变量的用途和限制？', 'CSS变量方便主题切换，运行时修改。IE不支持，需要fallback。可以和JS结合实现动态样式。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'JavaScript闭包的原理和常见应用？', '闭包可以访问外部函数变量，即使外部函数已返回。常见用于模块封装、函数工厂、事件处理。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'JS原型链继承的工作原理？', '每个对象都有__proto__指向构造函数的prototype，形成原型链。属性查找会沿链向上查找。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'this关键字的绑定规则？', '默认绑定、隐式绑定、显式绑定(call/apply/bind)、new绑定。箭头函数不绑定this，继承外层。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Event Loop的宏任务和微任务？', '事件循环每次先执行同步代码，然后执行所有微任务(Promise/MutationObserver)，再执行一个宏任务(定时器/DOM事件)。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Promise链式调用的特点？', 'then/catch/finally都会返回新Promise，可以链式调用。错误会沿着链传播。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'async/await的错误处理最佳实践？', '用try/catch包裹await语句，或链式调用.catch()。统一错误处理，区分业务和系统错误。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'ES6+箭头函数的限制有哪些？', '没有自己的this，不能作为构造函数，没有arguments对象，不能使用yield。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'JS解构赋值的高级用法？', '可以设置默认值，重命名变量，数组嵌套解构，结合扩展运算符等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'ES6 modules和CommonJS的区别？', 'ES modules是静态的，编译时加载。CommonJS是动态的，运行时加载。浏览器和Node.js都支持ESM了。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Proxy和Reflect的应用场景？', 'Proxy可以拦截对象操作，用于数据绑定、日志、验证等。Reflect提供默认行为，与Proxy配合使用。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Symbol的用途和特点？', 'Symbol可以创建唯一标识符，避免属性名冲突。可用于私有属性(虽不是真私有)、元编程。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'React Hooks的使用规则？', '只能在组件顶层调用，不能在条件/循环/嵌套函数中。必须以use开头命名。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'useState和useReducer的选择标准？', '简单状态用useState，复杂状态逻辑或状态依赖之前状态时用useReducer。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'useEffect和useLayoutEffect的区别？', 'useEffect在浏览器绘制后异步执行。useLayoutEffect在DOM更新后同步执行，会阻塞绘制。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'React Context的性能优化？', 'Provider的value如果是对象/数组会导致不必要的重渲染。可以拆分context或使用memoization。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'React Fiber架构解决了什么问题？', 'Fiber实现了可中断的渲染，可以高优先级任务优先处理，避免长时间阻塞主线程。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'React.memo和useMemo的区别？', 'React.memo是HOC，用于组件。useMemo是Hook，用于值的缓存。都用于避免不必要的计算。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'React Suspense的工作原理？', 'Suspense可以在组件等待数据时显示fallback。配合lazy用于代码分割，或用于数据获取。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Vue 3 Composition API的优势？', '更好的逻辑复用、TypeScript支持、更灵活的代码组织。选项式API适合简单场景，组合式API适合复杂逻辑。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Vue的响应式原理(Vue 2 vs Vue 3)？', 'Vue 2用Object.defineProperty，Vue 3用Proxy。Proxy支持监听数组和新增属性，性能更好。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Vue 3 v-model的变化？', 'Vue 3默认使用modelValue和update:modelValue，支持多个v-model绑定。移除了.sync修饰符。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Vue Router 4的新特性？', 'Composition API支持、动态路由、更好的导航守卫、TypeScript改进等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Pinia和Vuex的对比？', 'Pinia更轻量，API更简单，更好的TypeScript支持。Vuex已过时，推荐Pinia。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Vue自定义指令的应用场景？', '用于操作DOM元素，例如v-loading、v-permission等。封装可复用的DOM行为。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'npm/yarn/pnpm的区别？', 'pnpm更高效，通过硬链接节省磁盘。yarn有lockfile更早。npm是官方默认。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Webpack和Vite的对比？', 'Vite开发更快，基于ESM。Webpack生态更好，适合生产构建。新项目推荐Vite。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'CommonJS和ESM模块如何混合使用？', '在Node.js用type: "module"，使用import()或require()互操作。构建工具会处理兼容性。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Node.js Stream的类型和用途？', 'Readable/Writable/Duplex/Transform。用于处理大数据，不占用过多内存。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Express中间件的执行顺序？', '按注册顺序执行，next()调用下一个。错误处理中间件有四个参数(err, req, res, next)。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', '浏览器渲染流程的关键阶段？', '解析HTML构建DOM → 解析CSS构建CSSOM → 合成Render Tree → Layout布局 → Paint绘制 → Composite合成。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', '减少reflow和repaint的方法？', '避免频繁修改style，使用class批量修改，离线DOM操作，requestAnimationFrame，transform/opacity动画。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Web Storage和IndexedDB的选择？', 'Storage存储少量键值对，简单。IndexedDB存储大量结构化数据，支持事务和索引。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'XSS攻击的原理和防御？', 'XSS是注入脚本执行。防御：转义输出、CSP、HTTPOnly Cookie、输入验证。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'CORS配置的关键参数？', 'Access-Control-Allow-Origin、Methods、Headers、Credentials。前后端都要正确配置。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'TypeScript类型和接口的区别？', '类型可以使用|和&合并，接口可以扩展和合并。接口更适合定义对象结构。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'TypeScript泛型的用途？', '泛型提供类型安全的复用，适用于组件、工具函数、数据结构等，不指定具体类型。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'TypeScript Utility Types的常用类型？', 'Partial、Required、Pick、Omit、Record、Exclude、Extract、ReturnType等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'tsconfig.json的关键配置？', 'target、module、strict、jsx、outDir、baseUrl、paths等。根据项目需要调整。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'React/Vue性能优化的通用策略？', '减少不必要重渲染、虚拟列表、图片懒加载、代码分割、缓存、Web Worker等。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', '前端安全认证的常见方案？', 'JWT、Session Cookie、OAuth2、SSO等。根据场景选择，注意安全隐患。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'PWA的核心技术有哪些？', 'Service Worker、Manifest、HTTPS。可以离线访问、添加到桌面、推送通知。', 'medium', 'seed,frontend', 'frontend'],
  ['前端综合', '种子题', 'Web Components的组成部分？', 'Custom Elements、Shadow DOM、HTML Templates、HTML Imports(已过时)。提供原生组件化能力。', 'medium', 'seed,frontend', 'frontend']
];
