module.exports = [
  ['Go综合', '种子题', 'Go语言中defer的执行顺序和规则是什么？', 'defer采用后进先出(LIFO)顺序执行。当函数返回时，所有defer语句按注册顺序的逆序执行。defer常用于资源释放、解锁等清理操作。defer的参数值在注册时就计算了，而不是执行时。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中new和make的区别是什么？', 'new用于创建值类型的指针，分配内存并将值初始化为零值，返回*T。make用于创建引用类型(slice/map/channel)，会分配并初始化内部数据结构，返回T而非指针。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go slice的扩容机制是怎样的？', '当容量不足时，slice会自动扩容。容量<1024时每次翻倍，>=1024时每次增加25%。扩容时会创建新的底层数组，然后将原元素复制过去。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中string的不可变特性有什么优缺点？', 'string不可变意味着可以安全共享，同时便于缓存和并发访问。缺点是修改字符串会创建新副本，可能造成内存浪费。可以通过[]byte转换后修改。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go如何处理panic和recover？', 'panic用于抛出异常，函数执行立即停止，执行所有defer，然后返回错误。recover可以捕获panic，仅在defer函数中调用有效，可以阻止panic传播，让程序继续运行。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中的类型断言和类型转换有什么区别？', '类型断言用于接口类型，语法x.(T)，判断x是否为T类型。类型转换用于两个兼容的类型，语法T(x)，会改变内存表示。类型断言可能失败，需要ok idiom。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Goroutine的栈是如何管理的？', 'Goroutine初始栈大小为2KB，按需自动增长。使用分段栈或复制栈的方式管理，避免栈溢出问题，栈最大可达GB级。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'GMP调度模型的工作原理？', 'GMP是Go调度器的核心：G是Goroutine，M是操作系统线程，P是处理器（包含本地G队列）。M需要绑定P才能执行G，P负责调度本地队列的G。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', '如何防止Goroutine泄漏？', '常见的Goroutine泄漏情况是channel一直阻塞、死锁或没有退出条件。可以使用context取消、select加default分支、超时控制等方式防止。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', '什么是Goroutine池，什么时候用？', 'Goroutine池限制同时运行的Goroutine数量，防止资源耗尽。适用于大量并发任务场景，通过有缓冲channel实现令牌控制。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Work Stealing调度策略是如何工作的？', '当一个P的本地队列为空时，会尝试从其他P的本地队列偷取一半G来执行。这可以提高CPU利用率，平衡负载。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中如何避免和检测死锁？', '避免循环等待、互斥条件、请求保持条件、不可剥夺条件。使用go vet、-race检测工具，或者采用context超时机制。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go select语句的特性和使用场景？', 'select用于同时等待多个channel操作，随机选择一个就绪的执行。用于多路复用、超时控制、非阻塞操作等场景。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'nil channel的行为是什么？', '向nil channel发送或接收会永远阻塞。关闭nil channel会panic。常用于控制channel的开关。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', '缓冲channel和无缓冲channel的区别？', '无缓冲channel在发送和接收同时准备好时才完成，用于同步。有缓冲channel有容量，可以异步存储，用于解耦。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', '什么是Fan-Out和Fan-In模式？', 'Fan-Out是将任务分发给多个Goroutine，Fan-In是将多个channel的结果聚合到一个。结合使用可以实现并行处理。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中如何使用channel实现超时控制？', '使用time.After或time.NewTimer与select组合。例如select { case <-ch: ...; case <-time.After(1*time.Second): ... }', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go接口的鸭子类型特性是什么意思？', 'Go的接口实现是隐式的，只要类型有接口定义的方法就自动实现。无需显式声明implements，这提高了灵活性和复用性。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go 1.18引入的泛型有什么优势？', '泛型允许编写类型安全的通用代码，避免接口{}带来的类型断言和运行时错误。可以创建更抽象、可复用的库和数据结构。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中的组合优于继承如何理解？', 'Go没有类继承，通过嵌入struct实现组合。组合比继承更灵活，可以动态改变行为，避免继承层次过深的问题。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中如何实现枚举？', 'Go没有枚举类型，可以使用iota和const实现。例如type Status int; const (Idle Status = iota; Running; Stopped)。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go context包的主要用途是什么？', 'context用于在Goroutine间传递上下文、超时控制、取消信号、请求元数据。是并发控制的重要工具。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'sync.Map和普通map的区别？', 'sync.Map是并发安全的map，无需加锁。适合读多写少场景。普通map非并发安全，需要mutex保护。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'sync.WaitGroup的注意事项？', 'Add必须在Goroutine启动前调用，Done在Goroutine结束时调用，Wait会阻塞直到计数器归零。避免在Wait后再Add。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go database/sql连接池如何配置？', '通过SetMaxOpenConns、SetMaxIdleConns、SetConnMaxLifetime、SetConnMaxIdleTime配置，防止连接泄漏和资源耗尽。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go JSON序列化的常见问题？', '结构体字段首字母小写不可导出，tag可以控制字段名。time.Time需要特殊处理，空值可能被省略。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go slog包和log包的区别？', 'slog是结构化日志，支持JSON、文本格式，支持level和context。log是简单的文本日志，功能较弱。Go 1.21+推荐使用slog。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Gin/Echo中间件的洋葱模型是怎样的？', '中间件按注册顺序执行，处理请求后按逆序执行，形成洋葱一样的嵌套结构。可以用于认证、日志、错误处理等。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go Web框架参数绑定和验证最佳实践？', '使用struct tag绑定请求参数，结合validator库进行验证。避免直接使用map[string]interface{}。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Echo和Gin的主要区别是什么？', 'Gin更简单轻量，性能更好；Echo中间件更丰富，设计更现代。两者API风格不同，但功能类似，选择看团队偏好。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中JWT认证的实现方式？', '生成token用jwt库，验证时解析token中的声明并检查。token通常放在Authorization header或cookie中。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中如何做Table-Driven Test？', '创建测试用例数组，每个用例包含输入和期望输出，循环执行测试。提高代码复用和可维护性。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go基准测试的注意事项？', '用testing.B，重置计时器b.ResetTimer()，排除准备时间。运行足够多的次数获得稳定结果。使用b.N控制迭代次数。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go性能分析工具pprof如何使用？', '使用net/http/pprof或runtime/pprof收集CPU、内存、goroutine等profile，用go tool pprof分析，找出性能瓶颈。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go Data Race怎么检测和修复？', '用go test -race检测数据竞争。修复方法：加锁sync.Mutex、使用channel通信、使用原子操作sync/atomic。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go 1.21的synctest包有什么用？', 'synctest用于测试并发代码，可以虚拟控制时间，模拟延迟和超时，使测试更可靠。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中gRPC streaming的工作原理？', 'gRPC支持单向和双向流。基于HTTP/2，允许服务端和客户端持续发送消息。适合实时通信场景。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go微服务服务注册发现的常用方案？', '常用Consul、etcd、Nacos等。服务启动时注册，健康检查，客户端从注册中心获取服务地址。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go熔断和限流的实现思路？', '熔断可使用hystrix-go、sentinel-go。限流可用令牌桶、漏桶算法，或golang.org/x/time/rate。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go分布式链路追踪如何实现？', '集成OpenTelemetry或Jaeger，在请求间传递trace上下文，记录span信息，分析调用链。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go超时重试的最佳实践？', '使用context控制超时，指数退避策略，设置最大重试次数，区分可重试和不可重试错误。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go viper配置管理包的优势？', 'viper支持多种格式(YAML/TOML/JSON/ENV)，自动热加载，支持远程配置，优先级管理等功能。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go项目标准布局是什么？', 'cmd/放main包，internal/放私有代码，pkg/放可重用库，api/放API定义，configs/配置文件。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go服务如何优雅重启？', '接收SIGINT/SIGTERM信号，停止接收新请求，等待现有请求处理完成，然后关闭资源。用http.Server.Shutdown实现。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中protobuf的使用场景和注意事项？', 'protobuf用于跨语言API和序列化。相比JSON更小更快。注意版本兼容性，使用protoc生成Go代码。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Zap和Logrus日志库的对比？', 'Zap性能更好，是结构化日志的首选。Logrus更简单，API更友好，插件丰富。Zap更适合高性能场景。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'sync.Pool的作用和使用注意事项？', 'sync.Pool用于对象复用，减少GC压力。注意Pool中的对象随时可能被回收，不要依赖它存储状态。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go中如何实现不可变数据结构？', '通过构造函数、不导出字段、提供拷贝方法来保证不可变。使用value receiver而非pointer receiver。', 'medium', 'seed,go', 'go'],
  ['Go综合', '种子题', 'Go安全配置管理的最佳实践？', '不要硬编码密码，使用环境变量或Vault等密钥管理工具。在日志中隐藏敏感信息，加密传输。', 'medium', 'seed,go', 'go']
];
