module.exports = [
  ['Python综合', '基础', 'Python的可变和不可变类型分别有哪些？', '可变：list、dict、set；不可变：int、str、tuple、bool、float等。', 'easy', 'seed,python', 'python'],
  ['Python综合', '基础', 'Python的小整数池是什么？', 'Python缓存-5到256的小整数，避免频繁创建和销毁。', 'medium', 'seed,python', 'python'],
  ['Python综合', '基础', 'is和==的区别？', 'is比较内存地址；==比较值相等。', 'easy', 'seed,python', 'python'],
  ['Python综合', '基础', 'Python的内置数据结构有哪些？', 'list、dict、tuple、set、frozenset等。', 'easy', 'seed,python', 'python'],
  ['Python综合', '基础', 'Python的切片(slice)用法？', 'list[start:end:step]；支持负数索引。', 'easy', 'seed,python', 'python'],
  ['Python综合', '基础', 'Python的浅拷贝和深拷贝区别？', 'copy.copy()浅拷贝只复制容器，元素不变；copy.deepcopy()递归复制。', 'medium', 'seed,python', 'python'],
  ['Python综合', '基础', 'Python的垃圾回收机制？', '引用计数为主，分代回收为辅；循环引用由GC处理。', 'medium', 'seed,python', 'python'],
  ['Python综合', '基础', 'Python的自省机制？', 'dir()、type()、hasattr()、getattr()、isinstance()等。', 'medium', 'seed,python', 'python'],
  ['Python综合', '函数', 'Python函数的参数传递是值传递还是引用传递？', '对象引用传递；可变对象会影响外部，不可变不会。', 'medium', 'seed,python', 'python'],
  ['Python综合', '函数', '*args和**kwargs的区别？', '*args收集位置参数为元组，**kwargs收集关键字参数为字典。', 'easy', 'seed,python', 'python'],
  ['Python综合', '函数', '闭包的条件？', '嵌套函数、内部函数使用外部变量、返回内部函数。', 'medium', 'seed,python', 'python'],
  ['Python综合', '装饰器', '装饰器的本质和原理？', '装饰器是一个函数，接收函数返回函数；使用@语法糖。', 'medium', 'seed,python', 'python'],
  ['Python综合', '装饰器', '带参数的装饰器如何实现？', '再套一层函数，最外层接收参数。', 'medium', 'seed,python', 'python'],
  ['Python综合', '装饰器', 'functools.wraps的作用？', '保留原函数的名称、文档等元信息。', 'medium', 'seed,python', 'python'],
  ['Python综合', '迭代器生成器', '什么是迭代器协议？', '有__iter__()和__next__()方法。', 'medium', 'seed,python', 'python'],
  ['Python综合', '迭代器生成器', '生成器函数的特点？', '用yield暂停执行，下次从暂停处继续。', 'medium', 'seed,python', 'python'],
  ['Python综合', '迭代器生成器', '生成器表达式和列表推导式的区别？', '生成器表达式返回迭代器，节省内存；列表推导式立即计算。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'OOP', 'Python的新式类和经典类的区别？', 'Python 3全是新式类，默认继承object；新式类有super()、MRO等。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'OOP', 'Python的多重继承MRO是什么？', 'C3线性化算法决定搜索顺序；用类名.__mro__查看。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'OOP', 'super()的作用和原理？', '按MRO调用父类方法；super()等同于super(类, self)。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'OOP', 'Python的@property装饰器？', '将方法转为属性访问，控制getter/setter。', 'easy', 'seed,python', 'python'],
  ['Python综合', 'OOP', '什么是描述符协议？', '实现__get__、__set__、__delete__；property就是描述符。', 'hard', 'seed,python', 'python'],
  ['Python综合', 'OOP', '类方法、静态方法、实例方法的区别？', '实例方法第一个参数self，类方法第一个参数cls，静态方法无特殊参数。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'OOP', '__init__和__new__的区别？', '__new__创建实例，是静态方法；__init__初始化实例。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'OOP', 'Python的鸭子类型？', '不检查类型，看是否有方法；"走路像鸭子就是鸭子"。', 'medium', 'seed,python', 'python'],
  ['Python综合', '模块', 'Python的包和模块的区别？', '模块是.py文件，包是带__init__.py的目录。', 'easy', 'seed,python', 'python'],
  ['Python综合', '模块', 'Python的导入搜索路径？', 'sys.path；当前目录、PYTHONPATH、标准库路径等。', 'medium', 'seed,python', 'python'],
  ['Python综合', '模块', '相对导入和绝对导入的区别？', '相对导入用from . import xxx；绝对导入用完整路径。', 'medium', 'seed,python', 'python'],
  ['Python综合', '模块', '__all__的作用？', '控制from module import *时导入的内容。', 'medium', 'seed,python', 'python'],
  ['Python综合', '并发', '多线程GIL的影响？', '同一时间只有一个线程执行Python字节码；IO密集型多线程有用，CPU密集型用多进程。', 'medium', 'seed,python', 'python'],
  ['Python综合', '并发', 'threading和multiprocessing的区别？', '线程共享内存，开销小但受GIL限制；进程独立内存，开销大可利用多核。', 'medium', 'seed,python', 'python'],
  ['Python综合', '并发', '进程间通信方式？', 'Queue、Pipe、Manager、共享内存等。', 'medium', 'seed,python', 'python'],
  ['Python综合', '并发', '协程是什么？asyncio原理？', '协程是用户态轻量级线程；asyncio用事件循环调度。', 'medium', 'seed,python', 'python'],
  ['Python综合', '并发', 'async和await怎么用？', 'async定义协程，await等待可等待对象，需在事件循环中运行。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'Web框架', 'Flask的上下文？', '应用上下文和请求上下文；g对象、current_app、request等。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'Web框架', 'Django的MTV架构？', 'Model、Template、View；类似MVC。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'Web框架', 'FastAPI为什么快？', '基于Starlette+Pydantic；利用类型提示；支持异步。', 'medium', 'seed,python', 'python'],
  ['Python综合', '数据库', 'SQLAlchemy的核心和ORM？', 'Core是SQL抽象，ORM是对象关系映射。', 'medium', 'seed,python', 'python'],
  ['Python综合', '工具', 'pip的常用命令？', 'pip install、freeze、list等。', 'easy', 'seed,python', 'python'],
  ['Python综合', '工具', '虚拟环境的作用？', '隔离依赖；venv、conda、pyenv等工具。', 'easy', 'seed,python', 'python'],
  ['Python综合', '工具', 'Python的代码规范？', 'PEP8；Black自动格式化工具。', 'easy', 'seed,python', 'python'],
  ['Python综合', '工具', '日志模块logging的使用？', '配置logger、handler、formatter；按级别过滤。', 'medium', 'seed,python', 'python'],
  ['Python综合', '正则', 're模块常用函数？', 'match、search、findall、sub、compile等。', 'medium', 'seed,python', 'python'],
  ['Python综合', 'IO', '文件操作with语句的好处？', '自动关闭文件，异常安全。', 'easy', 'seed,python', 'python'],
  ['Python综合', 'IO', '文本模式和二进制模式区别？', '文本模式带编码解码，二进制模式原样读写。', 'easy', 'seed,python', 'python'],
  ['Python综合', '编码', 'Python 3的str和bytes？', 'str是Unicode，bytes是字节序列；encode/decode转换。', 'medium', 'seed,python', 'python'],
  ['Python综合', '魔术方法', '__str__和__repr__的区别？', '__str__用户友好，__repr__开发者友好；print调用__str__。', 'medium', 'seed,python', 'python'],
  ['Python综合', '魔术方法', '__getitem__、__len__有什么用？', '实现序列行为，支持len()、下标访问。', 'medium', 'seed,python', 'python'],
  ['Python综合', '其他', 'Python的上下文管理器？', 'with语句，__enter__和__exit__。', 'medium', 'seed,python', 'python']
];
