module.exports = [
  ['Python综合', '种子题', 'Python列表推导式的语法和优势？', '[x for x in iterable if condition]，简洁高效，比for循环append性能好，代码可读性高。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python装饰器的原理和应用？', '装饰器本质是函数，接收函数返回函数。常用场景：日志、计时、权限、缓存等。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中生成器和迭代器的区别？', '迭代器有__iter__和__next__。生成器是特殊迭代器，用yield更简洁，节省内存。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', '*args和**kwargs的用法？', '*args收集可变位置参数，**kwargs收集可变关键字参数。函数定义和调用时都能用。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python是值传递还是引用传递？', 'Python是对象引用传递。对于可变对象，函数内修改会影响外部；不可变对象则不会。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'GIL是什么？对Python多线程的影响？', '全局解释器锁，同一时刻只有一个线程执行。CPU密集型用多进程，IO密集型多线程也有用。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python的内存管理机制？', '引用计数为主，分代垃圾回收为辅。循环引用无法通过引用计数解决，需要GC。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', '深拷贝和浅拷贝的区别？', '浅拷贝只复制容器，元素引用不变。深拷贝递归复制所有对象。用copy模块。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python多进程和多线程的选择？', 'CPU密集型用多进程(multiprocessing)，规避GIL。IO密集型用多线程或asyncio。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python with语句的原理？', 'with实现了上下文管理器，__enter__和__exit__方法，安全管理资源，自动关闭。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python魔法方法有哪些常见？', '__init__、__str__、__repr__、__getitem__、__len__、__enter__、__exit__等。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中的property装饰器？', 'property将方法变成属性访问，可以实现getter/setter，控制属性访问和验证。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python类的多继承如何处理？', '使用C3线性化算法确定MRO顺序。super()按MRO调用。避免菱形继承的复杂性。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python的dataclasses模块？', 'dataclass装饰器自动生成__init__、__repr__等方法，减少样板代码。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'collections模块的常用数据类型？', 'namedtuple、deque、Counter、defaultdict、OrderedDict等，扩展内置类型功能。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'itertools模块的常用函数？', 'chain、cycle、product、permutations、combinations、islice等，用于迭代操作。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'functools的常用工具？', 'lru_cache、partial、reduce、wraps、singledispatch等，函数式编程工具。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python的日志模块logging最佳实践？', '配置logger、handler、formatter，按级别输出，不要用print，使用结构化日志。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Django MTV架构的含义？', 'Model-Template-View，类似MVC。Model是数据，Template是模板，View是逻辑处理。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Django ORM的select_related和prefetch_related？', 'select_related一对多正向查询用join。prefetch_related多对多或反向查询，分两次查询。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Django中间件的工作原理？', '中间件是钩子，处理请求和响应。按顺序处理请求，逆序处理响应。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Flask和Django的对比？', 'Flask微框架，灵活，适合小项目。Django全功能，内置管理后台、ORM等，适合大项目。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'FastAPI的优势是什么？', '基于现代Python类型提示，自动生成文档，性能好，支持异步，类型安全。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python Web框架的认证方案？', 'JWT、Session、OAuth2、Django Auth、FastAPI Security等，按需选择。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'NumPy数组和Python列表的区别？', 'NumPy数组同类型，内存连续，向量化操作，性能高。列表灵活但效率低。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Pandas DataFrame的常用操作？', '选择、过滤、groupby、merge、apply、map、透视表、时间序列处理等。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Pandas处理大数据的技巧？', '分块读取、优化数据类型、删除不需要的列、使用dask或vaex等库。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Matplotlib和Seaborn的关系？', 'Seaborn基于Matplotlib，提供更高API，默认样式更好看，适合统计绘图。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'asyncio的核心概念？', '事件循环、协程、awaitable对象。单线程并发，适合IO密集型任务。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'async/await语法的使用注意？', 'await只能在async函数中用，调用async函数返回协程对象，需交给事件循环。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'aiohttp和requests的区别？', 'requests是同步HTTP库。aiohttp是异步，配合asyncio使用，并发请求效率高。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python异步操作MySQL的库？', 'aiomysql、asyncmy等，配合asyncio使用，避免阻塞。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python测试框架有哪些？', 'unittest标准库、pytest更强大流行、nose等。推荐pytest。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'pytest的fixture如何工作？', 'fixture提供测试数据和依赖，可参数化，有作用域(函数/类/模块/会话)。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python虚拟环境的工具对比？', 'venv内置，conda数据科学友好，pipenv/poetry依赖和环境管理一体。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'requirements.txt和setup.py的区别？', 'requirements.txt列依赖。setup.py/pyproject.toml用于包分发安装。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python代码格式化和lint工具？', 'Black格式化，flake8/pylint/ruff检查，pre-commit钩子集成。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python类型提示的好处？', '提高可读性，IDE支持更好，静态检查工具(mypy)提前发现错误。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中的单例模式实现方式？', '模块导入、__new__方法、元类、装饰器。模块导入最简单常用。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中*和**的 unpack用法？', '列表/元组解包用*，字典解包用**。函数调用和字面量都能用。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python的可迭代对象和迭代器协议？', '可迭代有__iter__返回迭代器，迭代器有__next__方法。for循环会隐式使用。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中的上下文管理器除了with还能怎么用？', 'contextlib.contextmanager装饰器可以用yield创建简单上下文管理器。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python处理JSON的模块和注意事项？', 'json模块loads/dumps。注意日期、小数等类型需要自定义处理。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中pickle的安全风险？', '反序列化可能执行恶意代码。不信任的来源绝对不要用pickle，用JSON代替。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Celery的架构和使用场景？', 'Celery是任务队列，Producer→Broker→Worker→Backend。用于异步任务和定时任务。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中怎么处理大文件？', '逐行读取、分块处理、mmap映射内存、生成器，避免一次性加载。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python正则表达式模块re的常用函数？', 'match、search、findall、sub、split、compile预编译提高性能。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python中的鸭子类型哲学？', '不检查对象类型，看是否有需要的方法。"如果走起来像鸭子..."提高灵活性。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python描述符的作用和应用？', '描述符实现属性访问逻辑，property就是描述符。ORM字段、属性验证等。', 'medium', 'seed,python', 'python'],
  ['Python综合', '种子题', 'Python元编程的常用技术？', '元类、装饰器、exec/eval、__getattr__/__setattr__等动态特性。', 'medium', 'seed,python', 'python']
];
